---
contact_links:
  - name: Fairlens community discussions
    url: https://github.com/synthesized-io/fairlens/discussions
    about: Please ask and answer questions here.
  - name: Fairlens Documentation
    url: https://fairlens.readthedocs.io/en/latest/
    about: Checkout our latest documentation.
...
