# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = "0.1.0rc2.dev12+g435c3be.d20210805"
version_tuple = (0, 1, "0rc2", "dev12+g435c3be", "d20210805")
